name: Build IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install ldid dpkg
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo 'export THEOS=~/theos' >> $GITHUB_ENV

      - name: Set Build Variables
        run: |
          echo "TARGET=iphone:clang:latest:latest" >> $GITHUB_ENV
          echo "ARCHS=arm64" >> $GITHUB_ENV

      - name: Build DEB
        run: |
          export THEOS=~/theos
          make clean package

      - name: Convert DEB to IPA
        run: |
          export DEB=$(find . -name "*.deb" | head -n 1)
          if [ -z "$DEB" ]; then
            echo "No .deb file found. Packaging failed."
            exit 1
          fi

          rm -rf Payload
          mkdir -p Payload

          dpkg-deb -xv "$DEB" tmpdeb
          APP_PATH=$(find tmpdeb -type d -name "*.app" | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "No .app bundle found in the extracted .deb"
            exit 1
          fi
          
          echo "APP_PATH = $APP_PATH"
          ls -l "$APP_PATH"

          mv "$APP_PATH" Payload/

          zip -r ChatGPTLauncher.ipa Payload
          mkdir -p output
          mv ChatGPTLauncher.ipa output/

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ChatGPTLauncher-IPA
          path: output/ChatGPTLauncher.ipa
          if-no-files-found: error
          retention-days: 7

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          name: Rolling Release
          tag: release
          allowUpdates: true
          body: These are automatically updated builds of the latest commit.
          artifacts: output/ChatGPTLauncher.ipa
          token: ${{ secrets.GITHUB_TOKEN }}
